sudo apt-get install libcurl 
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libxml2 
sudo apt-get install libxml2-dev 
sudo apt-get install libgit2 
sudo apt-get install libgit2-dev
sudo apt-get install libssh2-1 
sudo apt-get install libssh2-1-dev
sudo apt-get install libssl
sudo apt-get install libssl-dev
sudo apt-get install libmagick++-dev
sudo apt-get install libv8-dev
