install.packages("devtools")
install.packages("reticulate")
install.packages("keras")
install.packages("shiny")
install.packages("shinyjs")
install.packages("V8")
install.packages("magick")
install.packages("imager")
install.packages("viridis")
install.packages("data.table")
install.packages("png")
install.packages("stringr")
install.packages("shinymanager")
install.packages("shinycustomloader")
install.packages("shiny.i18n")
install.packages("shinyWidgets")
install.packages("spatstat")
install.packages("rstudioapi")
install_miniconda(path = miniconda_path(), update = TRUE, force = FALSE)
conda_create("prio_retino", python_version = "3.10")
use_condaenv(condaenv = "prio_retino")
library(tensorflow)
install_tensorflow(version = "2.11.0", envname = "prio_retino")
py_install("image-quality-1.2.7/", envname = "prio_retino", pip = TRUE)
# if command above does not work use the following in shell
# sudo /home/shiny/.local/share/r-miniconda/envs/prio_retino/bin/python -m pip install -e image-quality-1.2.7/
py_install("matplotlib", envname = "prio_retino", pip = TRUE)
py_install("opencv-python~=3.4.2", envname = "prio_retino", pip = TRUE)
py_install("h5py~=3.7.0", envname = "prio_retino", pip = TRUE)
py_config()
py_available()
py_module_available("cv2")
py_module_available("imquality")
