library(rstudioapi)
library(data.table)
library(stringr)
library(reticulate)
library(tensorflow)
library(keras)
py_config()  
py_available()
py_module_available('cv2')
library(magick)
library(imager)
library(devtools)
setwd(dirname(getActiveDocumentContext()$path))
cv2<-import('cv2')
source_python('resize_images.py')
resize_images(location="../", name="test_img", extension="png", resize_location="../", desired_size = 1024)

