library(rstudioapi)
library(data.table)
library(stringr)
library(reticulate)
py_config()  
py_available()
py_module_available('cv2')
library(keras)
library(magick)
library(imager)
library(devtools)
setwd(dirname(getActiveDocumentContext()$path))
cv2<-import('cv2')
source_python('resize_images.py')
resize_images(location="../", name="0cae727cf119", extension="png", resize_location="../", desired_size = 1024)

